name: Bounty: Forum Expert Cryptography EXAMPLE
description: Click to start
title: "YOUR_NAME: Cryptography"
labels: "comment,hours,traditional,approval"
assignees:
  - twan-dev
body:
  - type: markdown
    attributes:
      value: |
        ## Eligibility
        This bounty is for Contributor or higher members of SCRF.
        ## Steps to Success
        - [ ]  Write a comment on 5 different posts in the Cryptography category on the SCRF Forum


  - type: textarea
    id: text
    attributes:
      label: Issue Text
      description: text goes here!
